---

install_path: /opt/arteria/

arteria_siswrap_env_root: /opt/arteria/arteria-siswrap-env
arteria_siswrap_path: "{{ install_path }}/arteria-siswrap-env"
arteria_siswrap_config_root: /etc/arteria/siswrap
arteria_siswrap_app_config: "{{ arteria_siswrap_config_root }}/app.config"
arteria_siswrap_logger_config: "{{ arteria_siswrap_config_root }}/logger.config"
sisyphus_path: "{{ arteria_siswrap_path }}/deps/sisyphus/"
sisyphus_git_repo: https://github.com/Molmed/sisyphus.git
sisyphus_repo_branch: master

runfolder_path: /data/{{ ansible_nodename }}/runfolders
arteria_bcl2fastq_env_root: /opt/arteria/arteria-bcl2fastq-env
arteria_bcl2fastq_config_root: /etc/arteria/bcl2fastq/
arteria_bcl2fastq_app_config: "{{ arteria_bcl2fastq_config_root }}/app.config"
arteria_bcl2fastq_logger_config: "{{ arteria_bcl2fastq_config_root }}/logger.config"
bcl2fastq_logs_path: /var/log/bcl2fastq/

# TODO: Temporary off, should be on if arteria_environment == `staging`
arteria_bcl2fastq_run_tests: False
arteria_siswrap_run_tests: False
