---
- name: select git sources
  set_fact:
    arteria_runfolder_sources_path: "/usr/src/arteria-runfolder"
  when: arteria_runfolder_sources == "git"

- name: select mounted sources
  set_fact:
    arteria_runfolder_sources_path: "/arteria/arteria-runfolder"
  when: arteria_runfolder_sources == "mount"

- name: get arteria-runfolder from git
  git:
    repo: "{{ arteria_runfolder_repo }}"
    dest: /usr/src/arteria-runfolder
    version: "{{ arteria_runfolder_version }}"
  when: arteria_runfolder_sources == "git"

- name: install arteria-runfolder requirements
  pip:
      requirements: "{{ arteria_runfolder_sources_path }}/requirements/dev"
      chdir: "{{ arteria_runfolder_sources_path }}"
      virtualenv: "{{ arteria_runfolder_env_root }}"
      virtualenv_command: /usr/local/bin/virtualenv
      state: present
      executable: "{{ arteria_runfolder_env_root }}/bin/pip"
      extra_args: "-U"

- name: install arteria-runfolder
  pip:
      name: .
      chdir: "{{ arteria_runfolder_sources_path }}"
      virtualenv: "{{ arteria_runfolder_env_root }}"
      virtualenv_command: /usr/local/bin/virtualenv
      state: present
      executable: "{{ arteria_runfolder_env_root }}/bin/pip"
      extra_args: "-U"

- name: change file owner of arteria-runfolder
  shell: chown -R {{ arteria_user }} {{ arteria_runfolder_env_root }}

