---
- name: install arteria-runfolder requirements
  pip:
      requirements: "{{ arteria_runfolder_sources_path }}/requirements/dev"
      chdir: "{{ arteria_runfolder_sources_path }}"
      virtualenv: "{{ arteria_runfolder_env_root }}"
      virtualenv_command: /usr/local/bin/virtualenv
      state: present
      executable: "{{ arteria_runfolder_env_root }}/bin/pip"
      extra_args: "-U"

- name: install arteria-runfolder
  pip:
      name: .
      chdir: "{{ arteria_runfolder_sources_path }}"
      virtualenv: "{{ arteria_runfolder_env_root }}"
      virtualenv_command: /usr/local/bin/virtualenv
      state: present
      executable: "{{ arteria_runfolder_env_root }}/bin/pip"
      extra_args: "-U"

