---

# By default (when arteria_sources == "git") we get sources from the 
# configured git repos and install from /usr/src.
# If arteria_sources == "mount", we fetch sources instead directly from /arteria.

# Select the source location to use:
- name: select git sources
  set_fact: 
    arteria_runfolder_sources_path: "/usr/src/arteria-runfolder"
    arteria_runfolder_core_sources_path: "/usr/src/arteria-core_runfolder"
  when: arteria_runfolder_sources == "git"

- name: select mounted sources 
  set_fact: 
    arteria_runfolder_sources_path: "/arteria/arteria-runfolder"
    arteria_runfolder_core_sources_path: "/arteria/arteria-core"
  when: arteria_runfolder_sources == "mount"

# Fetch sources if needed:
- name: get arteria-core from git for runfolder
  git:
    repo: "{{ arteria_runfolder_core_repo }}"
    dest: /usr/src/arteria-core_runfolder
    version: "{{ arteria_runfolder_core_version }}"
  when: arteria_runfolder_sources == "git"

- name: get arteria-runfolder from git
  git:
    repo: "{{ arteria_runfolder_repo }}"
    dest: /usr/src/arteria-runfolder
    version: "{{ arteria_runfolder_version }}"
  when: arteria_runfolder_sources == "git"

