---

- name: Get st2 token
  command: /bin/bash /arteria/arteria-packs/scripts/st2token
  register: st2token

- name: Setup virtualenv for arteria-packs
  command: /bin/bash -c "ST2_AUTH_TOKEN={{ st2token.stdout }} /arteria/arteria-packs/scripts/setup-virtualenv"

- name: Register arteria-packs
  command: /bin/bash -c "export ST2_AUTH_TOKEN={{ st2token.stdout }} && /arteria/arteria-packs/scripts/register"

