---

# TODO: Change this user name in a better way in the future..
- name: Change the system user from the default stanley to our provision user
  sudo: yes
  replace: regexp="^user = stanley$" replace="user = {{ st2_system_user }}" dest=/etc/st2/st2.conf backup=yes

- name: Change the system user's SSH key
  sudo: yes
  replace: regexp="^ssh_key_file = /home/stanley/.ssh/stanley_rsa$" replace="ssh_key_file = /home/{{ st2_system_user }}/.ssh/key" dest=/etc/st2/st2.conf backup=yes
  notify:
    - restart st2

- name: Create log dir for arteria
  sudo: yes
  file: path=/var/log/arteria/ state=directory owner={{ st2_system_user }} group={{ st2_system_user }} mode=0755

