---

- include: arteria_mailclient.yml
  tags: arteria_mailclient

- include: conf.yml
  tags: arteria_master_conf 

- name: Pause for 1 minute until stackstorm services are up and online
  pause: minutes=1

- include: register_components.yml
  tags: arteria_register_components 

- name: Ensure api is reachable from web-ui
  sudo: yes
  ini_file:
    dest=/etc/st2/st2.conf
    section=api
    option=allow_origin
    value=http://{{ st2_webui_host }}:8080
    backup=yes
  notify:
    - restart st2
  tags: arteria_master_conf
