---

arteria_disable_iptables: true
arteria_user: vagrant

# Default to "prod". If set to "staging" some roles might have a slightly different
# behavior, enabling debug mode and allowing extra integration tests capabilities.
arteria_environment: prod

