---
- name: Install st2 for arteria
  remote_user: vagrant
  hosts: master
  vars:
    st2_version: 0.13.2
    st2web_version: 0.13.2
    st2_system_user_in_sudoers: no
  roles:
    # Postgres requires that the en_US.UTF-8 locale is set - this fixes that
    - locale
    - mongodb
    - rabbitmq
    - mistral
    - st2
    - st2web
    - arteria

- name: Setup the testarteria1 node
  remote_user: vagrant
  sudo: true
  hosts: nodes
  vars:
    arteria_environment: staging
  roles:
    - { role: arteria_node, tags: ['arteria_node'] }
    - { role: bcl2fastq, tags: ['bcl2fastq'] }
    - { role: siswrap, tags: ['siswrap'] }
    - { role: runfolder, tags: ['runfolder'] }
    - sisyphus

- name: Setup test remote node
  remote_user: vagrant
  sudo: true
  hosts: remote
  roles:
    - sisyphus

