- name: Create actions directory
  sudo: true
  file:
    path: /etc/mistral/actions
    state: directory

- name: Clone Mistral actions repo
  sudo: true
  git:
    repo: https://github.com/StackStorm/st2mistral.git
    version: "{{ mistral_branch }}"
    dest: /etc/mistral/actions/st2mistral

- name: Install Mistral actions
  sudo: true
  shell: /opt/openstack/mistral/.venv/bin/python setup.py install
  args:
    chdir: /etc/mistral/actions/st2mistral
