- name: Install dependencies
  sudo: true
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - git
    - libssl-dev
    - libyaml-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - python-dev
    - python-pip

- name: Install pip virtualenv
  sudo: true
  pip:
    name: virtualenv
