---

arteria_runfolder_env_root: /opt/arteria/arteria-runfolder-env
arteria_runfolder_config_root: /etc/arteria/runfolder
arteria_runfolder_app_config: "{{ arteria_runfolder_config_root }}/app.config"
arteria_runfolder_logger_config: "{{ arteria_runfolder_config_root }}/logger.config"
runfolder_path: /data/{{ ansible_nodename }}/runfolders

