---
- name: Install st2 for arteria
  remote_user: vagrant
  hosts: master 
  vars:
    # the StackStorm version to install
    version: 0.11.2
  roles:
    - st2op
    - mongodb
    - rabbitmq
    - role: st2packages
      packages:
        - st2common
        - st2actions
        - st2api
        - st2auth
        - st2client
        - st2debug
        - st2reactor
    - mysql
    - mistral
    - st2web
    - arteria 
